### ISSUE TITLE
Unack'ed messages remain in queues despite .ack()'ing or .reply()'ing

### ISSUE THREAD

**Issue by 24601** [arobson/rabbot#33] opened 2016-08-06 05:07 UTC
We are experiencing an issue where unack'ed messages remain in queues despite .ack()'ing or .reply()'ing. It is indeterminate (so far, we are debugging) when this occurs (but it occurs very frequently). 

Sometimes messages are ack'ed and sometimes they are not and remain in the queue as unacked messages until they expire and head to dlx. 

We have done a lot of debugging and testing and we are beginning to suspect that in certain situations (e.g. under heavy load) that the delayed ack'ing of the rabbot library may not be occurring for some reason. 

We are as certain as we can be (e.g. as close to absolutely as is possible as a human) that every message is being ack'ed by the .handle on the server end, we have counted messages in and counted acks and they _always_ have matched up. 

Could someone please explain the nature of/methodology behind the "delayed" ack (the documentation mentions that acks are not sent immediately, this is what I am referring to)? 

I looked in the source but it was not obvious where this batching was occurring or how, we suspect a node run loop or tick issue either in node or other libs we include might be interfering with the rabbot library's deferred acking framework. 

This would help us further in our debugging to fully understand why there are situations where messages remain unack'ed in rabbit even though we have assuredly called msg.ack(). 

Thank you.

EDIT TO ADD: I have also taken traces at the network level (wireshark) and seen an disturbing absence of AMQP ACKs on the wire (using the AMQP protocol decoder so these are not being confused with TCP ACKs) while this has happened/when it happens, but we have verified that ACK is being called, so somewhere between us calling msg.ack() and the wire it is being lost (or never created?).

EDIT TO ADD (Part Deux): enabling noBatch mode on the queue in question completely prevents this issue, not a great solution performance wise but does fix the issue, which further indicates some problem with ACK batching being the issue. 

(Including @GitTristan)

**Comment by arobson** [comment] 2016-08-10 13:26
@24601 a few things could be causing this but I'll start by saying that what you're experiencing is, to my knowledge, isolated. Let's see if we can work through possible causes and eliminate them systematically. It would be helpful for me also if I could reproduce this so if we can take your setup and make it generic enough to share code to repro the scenario that would go a long way to helping me fix it.

### why batch at all
As you saw, noBatch works so why batch? Without it, an ack must be sent for every individual message you receive. This increases load on your machine, the network and the rabbit broker. Your entire system will become significantly slower as a result. Batching allows the consumer to say "I have processed all messages up to N" and the broker then releases those from the queue permanently.

### how batching is implemented in AMQP
Unfortunately AMQP's batching approach is unforgiving and complex. You can only acknowledge up to a message id since your last acknowledgement with no gaps. This means you can never nack a message from a previously ack'd range or ack part of a set or any of that. It's important to understand that complete ranges must be acknowledge at a time in order to understand everything that can go very wrong when using batch acknowledgements :)

### avoid unbound I/O in handlers
If you are processing messages using I/O calls with broad degrees of variance you may need to add timeouts to these to prevent messages in a batch sequence from ha fining indefinitely and keeping the batching mechanism form being able to resolve a sequence indefinitely. If you receive 1000 messages but an early message hangs the batching will get stuck waiting.

### always handle exceptions in handlers
Not catching exceptions in handlers has tripped up a lot of users. Because you're in a callback you don't get an exception and the message doesn't get nack'd for you so it's never resolved for the batch and then the entire batch hangs indefinitely.

### always ack, nack or reject in handlers
Sounds like you're doing this but it's important to be certain that there is no edge case for a handler to exit without having resolved the message in one of these three ways or the batching mechanism will hang.

### limit ingress
It is possible that the event loop could get overwhelmed due to the high volume of incoming messages, handler invocations and I/O callbacks such that the batching intervals aren't evaluating frequently enough to resolve the batches. The batching runs on an interval and itself relies on callbacks to resolve the tags for the outstanding messages. I haven't seen this myself yet but then we also limit the # of messages our services get per queue for other reasons. In general, letting rabbit deliver an unlimited # of messages to your service can be very bad. If the service goes down, the broker has to requeue all the unack'd messages leading to a lot of broker churn and possible message reordering. We'd rather run multiple instances of a service with smaller batch sizes and keep the risk of instance failure small.

Let's start with those. Let me know if that helps. The quickest thing to try would be limiting the number of messages your service is getting per queue at a time and go from there.

**Comment by ryanwilliamquinn** [comment] 2016-08-11 22:32
I'm seeing a similar issue. I don't know if this helps, but in the rabbot tests, I switched `autoDelete` to `false` for all of the queues in `spec/integration/configuration.js`. This is what my rabbitmq admin looks like for the relevant queues after the tests have run once:

![image](https://cloud.githubusercontent.com/assets/245794/17607141/a939f674-5fd8-11e6-89aa-88b18736a5e7.png)

That is likely expected behavior for some of those tests, I will try to take a closer look now.

**Comment by arobson** [comment] 2016-09-06 12:47
@ryanwilliamquinn - I've done the same. I'm not seeing the large amounts left in the hash queues that you're showing. Have you tried running the integration tests prefixed with `DEBUG=rabbot.acknack`? It will let you see debug output for the part of rabbot that's resolving the batching.

In general I haven't run into this and haven't had any luck reproducing this particular issue but it may be a combination of system load, environment factors and configuration.

**Comment by ryanwilliamquinn** [comment] 2016-10-14 18:47
Hey @arobson, I created a simple test case that reproduces the issue for me consistently.  The code is here: https://github.com/ryanwilliamquinn/rabbot/tree/ack-timeout

Specifically, there are two scenarios, based on how quickly `rabbit.shutdown()` is called after messages are processed.  See comments on the `after` methods here: https://github.com/ryanwilliamquinn/rabbot/blob/ack-timeout/spec/integration/integration.spec.js#L125

If I run `gulp` with the after method that looks like this: 
```		
after( function() {
      return rabbit.shutdown()
} );
```
I end up with messages that I attempted to ack still in the queue after the test finishes.

If I run `gulp` with the after method that looks like this:
```
after( function() {
      return new Promise(function(resolve) {
        setTimeout(function() {
          resolve()
        }, 1000)
      })
      .then(function () {
        return rabbit.shutdown()
      })
} );
```
then I get the expected behavior.

Let me know if you see the same issues.  I am running the tests against the provided docker rabbitmq instance.

**Comment by djMax** [comment] 2016-10-17 17:20
Is there a way to either trigger a flush of the ack/nack batch or to wait until it has completed? I'm also seeing the "setTimeout" solution working, but I don't like it.

**Comment by djMax** [comment] 2016-10-17 17:34
This is pretty gross, but less so than setTimeout, IMHO:

```
  if (queue.lastQueue.messages && queue.lastQueue.messages.length) {
    await new Promise((accept) => {
      queue.lastQueue.messages.on('empty', () => accept());
    });
  }
```

**Comment by djMax** [comment] 2016-10-17 17:49
Gross workaround:
```
  if (queue.lastQueue.messages.messages && queue.lastQueue.messages.messages.length) {
    await new Promise((accept) => {
      const l = queue.lastQueue.messages
        .on('empty', () => accept())
        .once();
    });
  }
```

**Comment by arobson** [comment] 2016-10-17 19:57
@djMax - thank you for all the time you're putting in. At one point, the shutdown was _supposed_ to ensure that, if possible, the queues and their channels would not get closed while their were outstanding messages waiting for any kind of resolution. I've clearly done something to break this at some point but I haven't had time to dig into finding out when I introduced the latest breaking change to it.

You're thinking along the right lines, however. The queue FSM should be listening for the empty event (if there are any messages in that batch at the time a shutdown has been called) before continuing with the shutdown process.

**Comment by djMax** [comment] 2016-10-17 20:13
pffft, it's a lot less time than I'd be putting in if you hadn't written all this. So no thanks for me, but happy to dig or help any way you need.

**Comment by arobson** [comment] 2016-12-30 02:28
@djMax @ryanwilliamquinn @24601 Unfortunately it looks like the promise for the ack on the channel resolves before the server has completed/resolved the action. When closing the channel, this could cause race conditions which would result in some or all messages being returned to the queue. I put a setTimeout in that delays when the batching mechanism emits the empty event that lets the queue know that its safe to close the queue's channel.

After doing this, I was unable to repro the issues even in 100 consecutive test runs. I'm hopeful this means that it will be enough to resolve the condition for other configurations/broker set ups.

**Closed** 2016-12-30 02:36 UTC
